version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - COURIER_API_KEY=${COURIER_API_KEY}
      - COURIER_CLIENT_KEY=${COURIER_CLIENT_KEY}
      - COURIER_TENANT_ID=${COURIER_TENANT_ID}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - REACT_APP_COURIER_CLIENT_KEY=${REACT_APP_COURIER_CLIENT_KEY}
      - REACT_APP_COURIER_TENANT_ID=${REACT_APP_COURIER_TENANT_ID}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
